# Database configuration
spring.datasource.url=jdbc:sqlserver://localhost:55538;databaseName=NoteKeeping;encrypt=false
spring.datasource.username=Khushi14
spring.datasource.password=Khushi14
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Increase request size limits to support base64 image uploads
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
